### ISSUE TITLE
Implement MVC Project Structure

### ISSUE THREAD

**Issue by n-aggarwal** [n-aggarwal/comp-333-3-backend#11]
Title.

**Comment by n-aggarwal** [comment]
https://code.tutsplus.com/how-to-build-a-simple-rest-api-in-php--cms-37000t

**Comment by ananafrida** [comment]
![image](https://github.com/n-aggarwal/comp-333-3-backend/assets/58756224/fd4ca658-ddf1-485f-9aa7-a879f42d8fe2)
